[package]
name = "fusb302b"
version = "0.0.1"
edition = "2021"
description = "FUSB302B driver for `usb-pd` library."
documentation = "https://docs.rs/fusb302b"
repository = "https://github.com/fmckeogh/usb-pd-rs"
homepage = "https://github.com/fmckeogh/usb-pd-rs"
license = "MIT"
keywords = ["nostd", "usb-pd", "driver", "embedded", "fusb302b"]

[dependencies]
byteorder = { version = "1.5.0", default-features = false }
embedded-hal-async = "1.0.0"
heapless = { version = "0.8.0", features = ["defmt-03"] }
defmt = "0.3.5"
paste = "1.0.14"
proc-bitfield = "0.3.1"
embassy-time = "0.3.0"

usb-pd = { path = "../usb-pd" }
